site_name: jaxkineticmodel documentation
nav:
  - Home: index.md
  - Building models: building_models.md
  - Loading SBML models: SBML.md
  - Training models: training_models.md
  - Simulated-DBTL: simulated-DBTL.md
  - Custom models: glycolysis.md

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - markdown_include.include:
      base_path: docs

  
theme: readthedocs
