site_name: JaxKineticModel documentation
nav:
  - Home: index.md
  - SBML models: SBML.md
  - Building models: building_models.md

  - Simulated-DBTL: simulated-DBTL.md
  - Training models: training_models.md
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.0/es5/tex-mml-chtml.js
  
markdown_extensions:
  - admonition
  - codehilite
  - footnotes



  
theme: readthedocs
